/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.ruben.pe.cprecentacion;
import com.ruben.pe.cmodelo.Compania;
import con.ruben.pe.cnegocio.ConpaniaBO;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.text.ParseException;
import javax.swing.JOptionPane;
/**
 *
 * @author ACER
 */
public class Conpania extends javax.swing.JPanel {
    ConpaniaBO  tdbo = new  ConpaniaBO();
    Compania dd = new Compania();
    String idconpania;
    /**
     * Creates new form Conpania
     */
    public Conpania() {
        initComponents();
        listar_conpania ();
    }
    
    public void listar_conpania (){
        tdbo.listarConpania(tablaConpania);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CONPANIA1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNmroCon = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaConpania = new javax.swing.JTable();
        BTNeliminar = new javax.swing.JButton();
        BtnGuardar = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();

        CONPANIA1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setText("CONPAÑIA");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Numero de Conpañia");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nombre");

        TxtNmroCon.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TxtNombre.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreActionPerformed(evt);
            }
        });

        tablaConpania.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaConpania.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaConpaniaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaConpania);

        BTNeliminar.setBackground(new java.awt.Color(204, 204, 204));
        BTNeliminar.setForeground(new java.awt.Color(102, 102, 102));
        BTNeliminar.setText("ELIMINAR");
        BTNeliminar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNeliminarActionPerformed(evt);
            }
        });

        BtnGuardar.setBackground(new java.awt.Color(204, 204, 204));
        BtnGuardar.setForeground(new java.awt.Color(102, 102, 102));
        BtnGuardar.setText("GUARDAR");
        BtnGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        BtnModificar.setBackground(new java.awt.Color(204, 204, 204));
        BtnModificar.setForeground(new java.awt.Color(102, 102, 102));
        BtnModificar.setText("MODIFICAR");
        BtnModificar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CONPANIA1Layout = new javax.swing.GroupLayout(CONPANIA1);
        CONPANIA1.setLayout(CONPANIA1Layout);
        CONPANIA1Layout.setHorizontalGroup(
            CONPANIA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONPANIA1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(406, 406, 406))
            .addGroup(CONPANIA1Layout.createSequentialGroup()
                .addGroup(CONPANIA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CONPANIA1Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(CONPANIA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNmroCon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CONPANIA1Layout.createSequentialGroup()
                                .addComponent(BtnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                                .addComponent(BTNeliminar))))
                    .addGroup(CONPANIA1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(BtnModificar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        CONPANIA1Layout.setVerticalGroup(
            CONPANIA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONPANIA1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(CONPANIA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CONPANIA1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(TxtNmroCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addGroup(CONPANIA1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNeliminar)
                            .addComponent(BtnGuardar))
                        .addGap(18, 18, 18)
                        .addComponent(BtnModificar))
                    .addGroup(CONPANIA1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CONPANIA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CONPANIA1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        // TODO add your handling code here:
          try {
        // Crear un objeto Datos_Documento
        Compania dd = new Compania();
        
        // Obtener los valores de los campos de texto del formulario
        
        dd.setNmroconpania(Integer.parseInt(TxtNmroCon.getText()));
        dd.setNombre(TxtNombre.getText());
        
        // Crear un objeto de negocio y llamar al método para agregar datos
        ConpaniaBO tdbo = new ConpaniaBO();
        String mensaje = tdbo.agregarCliente(dd);
        
        listar_conpania();
        // Mostrar mensaje de éxito
        JOptionPane.showMessageDialog(this, mensaje);
        
        // Limpiar los campos de texto después de guardar
        limpiarCampos();
        
    } catch (SQLException e) {
        // Manejo de excepciones
        JOptionPane.showMessageDialog(this, "Error al guardar los datos: " + e.getMessage());
    } catch (NumberFormatException e) {
        // Manejo de excepciones para formato de número
        JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos.");
    }
        
        
        
        
        
        
        
    }//GEN-LAST:event_BtnGuardarActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
        // TODO add your handling code here:
        
        if (idconpania != null && !idconpania.isEmpty()) {
        try {
            dd.setId_compania(Integer.parseInt(idconpania));
            dd.setNmroconpania(Integer.parseInt(TxtNmroCon.getText()));
            dd.setNombre(TxtNombre.getText()); 
            
            String mensaje = tdbo.modificarCliente(dd);
            
            JOptionPane.showMessageDialog(this, mensaje);
            
            listar_conpania();
            
            limpiarCampos();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: Verifique que todos los campos sean válidos.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro para modificar.");
    }
    }//GEN-LAST:event_BtnModificarActionPerformed

    private void BTNeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNeliminarActionPerformed
        // TODO add your handling code here:
        if (idconpania != null && !idconpania.isEmpty()) {
            try {
                // Establecer el ID del documento a eliminar
                dd.setId_compania(Integer.parseInt(idconpania));
                
                // Llamar al método de negocio para eliminar el documento
                String mensaje = tdbo.eliminarConpania(dd);
                
                // Mostrar mensaje de éxito
                JOptionPane.showMessageDialog(this, mensaje);
                
                listar_conpania();

                
                // Limpiar campos
                limpiarCampos();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: ID no válido.");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error de base de datos: " + e.getMessage());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error inesperado: " + e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione un registro para eliminar.");
        }
    }//GEN-LAST:event_BTNeliminarActionPerformed

    private void tablaConpaniaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaConpaniaMouseClicked
        // TODO add your handling code here:
        int seleccion  = tablaConpania.rowAtPoint(evt.getPoint());
        idconpania = tablaConpania.getValueAt(seleccion, 0)+"";
        
        
        TxtNombre.setText(tablaConpania.getValueAt(seleccion, 1)+"");
        TxtNmroCon.setText(tablaConpania.getValueAt(seleccion, 2)+"");
        
        
        
        
        
        System.out.println(seleccion);
        
        
        
    }//GEN-LAST:event_tablaConpaniaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNeliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnModificar;
    private javax.swing.JPanel CONPANIA1;
    private javax.swing.JTextField TxtNmroCon;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaConpania;
    // End of variables declaration//GEN-END:variables
private void limpiarCampos() {
        TxtNombre.setText("");
        TxtNmroCon.setText("");
        
}
}
